### ISSUE TITLE
reset all blocks

### ISSUE THREAD

**Issue by itsMarkme** [TimeCodings/CubicCountdown#1]
hi good day to you sir, i have an issue or a request. After the countdown is i want to reset all blocks inside on the bedrock instead of only a selected layer :) thank you in advance for your response :)

**Comment by TimeCodings** [comment]
Hello, thank you for your request! To reset the whole cube after the countdown expires, simply select the lower right corner and the upper left corner in the setup so that the whole cube has been marked. Now complete the setup and if you have installed the latest update, everything should work!

**Comment by itsMarkme** [comment]
Thank you! Appreciated for resposing asap. Thank you sir!

**Comment by Sandinurdiansyah** [comment]
> Hello, thank you for your request! To reset the whole cube after the countdown expires, simply select the lower right corner and the upper left corner in the setup so that the whole cube has been marked. Now complete the setup and if you have installed the latest update, everything should work!

I followed these instructions and got a problem, when the block is still filled to 1 and not full on the selected layer, the countdown will start. pls see video. thanks before sir

https://github.com/TimeCodings/CubicCountdown/assets/109714557/d65349d4-f923-47a6-ba26-b7f3b5f64461

**Comment by TimeCodings** [comment]
> > Hello, thank you for your request! To reset the whole cube after the countdown expires, simply select the lower right corner and the upper left corner in the setup so that the whole cube has been marked. Now complete the setup and if you have installed the latest update, everything should work!
> 
> I followed these instructions and got a problem, when the block is still filled to 1 and not full on the selected layer, the countdown will start. pls see video. thanks before sir
> 
>  2023-09-04.00-27-35_2.mp4

Do you have any other maps? And are there any errors in the console?

**Comment by Sandinurdiansyah** [comment]
> > > Hello, thank you for your request! To reset the whole cube after the countdown expires, simply select the lower right corner and the upper left corner in the setup so that the whole cube has been marked. Now complete the setup and if you have installed the latest update, everything should work!
> > 
> > 
> > I followed these instructions and got a problem, when the block is still filled to 1 and not full on the selected layer, the countdown will start. pls see video. thanks before sir
> > 2023-09-04.00-27-35_2.mp4
> 
> Do you have any other maps? And are there any errors in the console?

Thank you for responding, sir. I'm not sure if there's an error on my server or with my Minecraft. I'm a bit of a newbie with this. I hope you can take a look at the screenshots I provided. There, you'll find a list of worlds, a list of plugins, and the server screen


![Screenshot_1](https://github.com/TimeCodings/CubicCountdown/assets/109714557/18335412-98de-41eb-baba-da63cd4b6494)
![Screenshot_2](https://github.com/TimeCodings/CubicCountdown/assets/109714557/ba1f0033-52a8-432b-bd26-f82e34ad3485)
![Screenshot_3](https://github.com/TimeCodings/CubicCountdown/assets/109714557/abfafab6-72e9-4b01-a06f-4fe197f61a49)

**Comment by vinhvuive389** [comment]
Do you know the block building orders sent to you by others and be able to watch the process of how those blocks build themselves?

**Comment by TimeCodings** [comment]
This feature is work in progress

**Comment by TimeCodings** [comment]
Issue closed - Moved to discord

**Comment by itsMarkme** [comment]
Im back again sir :) Do you have a plugins where the tiktok live chat is connected on minecraft chat?

**Comment by TimeCodings** [comment]
You can easily do that in the Actions and Events section of Tikfinity without any plugin

**Comment by itsMarkme** [comment]
I didnt figured it out yet😂 but it's okay, nevermind
