### ISSUE TITLE
Infinite counter when two or more players on server near box

### ISSUE THREAD

**Issue by kurovskyiii** [TimeCodings/CubicCountdown#4]
Starting from 1.2.2 version when there are two or more players on server near a box, when the box is filled and the countdown begins, it continually ticks and slows down until the server crashes. Fix this please. On version 1.2.1 all is good. Also, big thanks for your plugin!

**Comment by TimeCodings** [comment]
Hello, thank you for the report! Would it be possible to send me the error that occurred before the crash? Thanks in advance!

**Comment by kurovskyiii** [comment]
> Hello, thank you for the report! Would it be possible to send me the error that occurred before the crash? Thanks in advance!

It ran out of memory when I enabled firework effect on clearing box after win, because fireworks were constantly spawning.
But If it's disabled, there is no server crash, just win counter is constantly updating and titles are constantly showing until I stop the server.

**Comment by kurovskyiii** [comment]
To reproduce the error, just try to join the server from two clients simultaneously, and fill a box to trigger the countdown.

**Comment by TimeCodings** [comment]
Thanks! I will try it out

**Comment by kurovskyiii** [comment]
Thank you! Looking forward to the news)

**Comment by TimeCodings** [comment]
> Thank you! Looking forward to the news)

Fixed! The .jar was updated. Download the newest one here: https://github.com/TimeCodings/CubicCountdown/releases/tag/v1.2.3_BETA

**Comment by kurovskyiii** [comment]
> > Thank you! Looking forward to the news)
> 
> Fixed! The .jar was updated. Download the newest one here: https://github.com/TimeCodings/CubicCountdown/releases/tag/v1.2.3_BETA

Thanks a lot! I'm so excited to see how fast you have fixed it)
I also have a small question. Is there a command to reset win/lose count for a box? It will be useful when I start a new "live stream" and want counters to be 0

**Comment by TimeCodings** [comment]
> > > Thank you! Looking forward to the news)
> > 
> > 
> > Fixed! The .jar was updated. Download the newest one here: https://github.com/TimeCodings/CubicCountdown/releases/tag/v1.2.3_BETA
> 
> Thanks a lot! I'm so excited to see how fast you have fixed it) I also have a small question. Is there a command to reset win/lose count for a box? It will be useful when I start a new "live stream" and want counters to be 0

In the last update I already added placeholders just for the session, which can be applied to the title, action bar,... in the Config.yml. Optionally, all Wins/Loses/Helps can also be reset with /cc setEntry Cube.CUBENAME.Win/Lose/HelpCounter 0

**Comment by kurovskyiii** [comment]
> In the last update I already added placeholders just for the session, which can be applied to the title, action bar,... in the Config.yml. Optionally, all Wins/Loses/Helps can also be reset with /cc setEntry Cube.CUBENAME.Win/Lose/HelpCounter 0

Thanks for the command! I know about the latest update with sessions, but as I understand, I should always restart a server to reset a session, right? It would be better to have just a single command to do that thing..
